# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\moham\BreastCancerDeskTop\Controller\information.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidget,QVBoxLayout,QHBoxLayout,QGroupBox,QTableWidgetItem,QPushButton
import sys


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1920, 1100)
        Dialog.setStyleSheet("\n"
"background-color:qlineargradient(spread:pad, x1:0.091, y1:0.101636, x2:0.991379, y2:0.977, stop:0 rgba(209, 107, 165, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(1920, 1100, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 90, 381, 601))
        self.label_2.setStyleSheet("background-color:rgb(255,255,255);\n"
"border-radius:20px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(560, 60, 151, 141))
        self.label_3.setStyleSheet("background-color:rgb(255,255,255);\n"
"border-radius:20px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.LogOut = QtWidgets.QPushButton(Dialog)
        self.LogOut.setGeometry(QtCore.QRect(90, 20, 93, 28))
        self.LogOut.setStyleSheet("QPushButton#LogOut{\n"
"    Background-color:rgba(85,98,112,255);\n"
"    color:rgba(255,255,255,200);\n"
"    border-radius:5px;\n"
"} \n"
"QPushButton#LogOut:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(254, 81, 171, 0.8);\n"
"    background-position:calc(100% - 10px)center;\n"
"}\n"
"QPushButton#LogOut:hover{\n"
"    background-color:rgba(254, 81, 171, 0.8)\n"
"}")
        self.LogOut.setObjectName("LogOut")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(560, 230, 800, 400))
        self.tableWidget.setStyleSheet("border-radius : 20px;\n"
"background-color:rgb(255,255,255);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.Addpatient = QtWidgets.QPushButton(Dialog)
        self.Addpatient.setGeometry(QtCore.QRect(1250, 590, 93, 28))
        self.Addpatient.setStyleSheet("QPushButton#Addpatient{\n"
"    Background-color:rgba(85,98,112,255);\n"
"    color:rgba(255,255,255,200);\n"
"    border-radius:5px;\n"
"} \n"
"QPushButton#Addpatient:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(254, 81, 171, 0.8);\n"
"    background-position:calc(100% - 10px)center;\n"
"}\n"
"QPushButton#Addpatient:hover{\n"
"    background-color:rgba(254, 81, 171, 0.8)\n"
"}")
        self.Addpatient.setObjectName("Addpatient")
        self.deletepatient = QtWidgets.QPushButton(Dialog)
        self.deletepatient.setGeometry(QtCore.QRect(1150, 590, 93, 28))
        self.deletepatient.setStyleSheet("QPushButton#deletepatient{\n"
"    Background-color:rgba(85,98,112,255);\n"
"    color:rgba(255,255,255,200);\n"
"    border-radius:5px;\n"
"} \n"
"QPushButton#deletepatient:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(254, 81, 171, 0.8);\n"
"    background-position:calc(100% - 10px)center;\n"
"}\n"
"QPushButton#deletepatient:hover{\n"
"    background-color:rgba(254, 81, 171, 0.8)\n"
"}")
        self.deletepatient.setObjectName("deletepatient")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(600, 70, 91, 51))
        font = QtGui.QFont()
        font.setFamily("12 Calibri")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"font: 16pt bold \"Calibri\";")
        self.label_9.setObjectName("label_9")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(870, 50, 151, 141))
        self.label_6.setStyleSheet("background-color:rgb(255,255,255);\n"
"border-radius:20px;")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(890, 60, 111, 51))
        font = QtGui.QFont()
        font.setFamily("12 Calibri")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"font: 16pt bold \"Calibri\";")
        self.label_10.setObjectName("label_10")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(1180, 50, 151, 141))
        self.label_7.setStyleSheet("background-color:rgb(255,255,255);\n"
"border-radius:20px;")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(1220, 60, 91, 51))
        font = QtGui.QFont()
        font.setFamily("12 Calibri")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"font: 16pt bold \"Calibri\";")
        self.label_11.setObjectName("label_11")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "TextLabel"))
        self.LogOut.setText(_translate("Dialog", "LogOut"))
        self.Addpatient.setText(_translate("Dialog", "Add"))
        self.deletepatient.setText(_translate("Dialog", "Delete"))
        self.label_9.setText(_translate("Dialog", "Low"))
        self.label_10.setText(_translate("Dialog", "Medium"))
        self.label_11.setText(_translate("Dialog", "Hard"))
    # the method of load products
    '''def loadProducts(self):
        self.ui.tableWidget.setRowCount(row)
        self.ui.tableWidget.setColumnCount(column)'''
'''------------------------------------main------------------------------------------'''

app = QtWidgets.QApplication(sys.argv)
win = QtWidgets.QWidget()
ui = Ui_Dialog()
ui.setupUi(win)
#-----------Table--------------
column = 10
def Table_info():
    vbox = QVBoxLayout()
    Table_information = [{'Id':'1', 'Name':'mmm' ,'BLABLA':'sss'},
        {'Id': '2', 'Name': 'ss', 'BLABLA': 'sss'},
         {'Id': '3', 'Name': 'dd', 'BLABLA': 'aa'},
        {'Id': '4', 'Name': 'fff', 'BLABLA': 'ww'},]

    tb_row = ui.tableWidget.setRowCount(len(Table_information))
    vbox.addWidget(tb_row)
    tb_col = ui.tableWidget.setColumnCount(column)
    vbox.addWidget(tb_col)
    ui.tableWidget.setHorizontalHeaderLabels(('Id', 'Name', 'BLABLA'))
    ui.tableWidget.setFixedSize(800,300)
    id_width = ui.tableWidget.setColumnWidth(0, 50) #set the id column width
    vbox.addWidget(id_width)
    #fill the data
    # ya zhz you can use a list of the dictionaray to retriev the data from the data base
    index = 0   # the number of the keys in the dictionary from data base

    for i in range(column):
        ui.tableWidget.setColumnWidth(i, 80)

    for info in Table_information:

        ui.tableWidget.setItem(index,0,QTableWidgetItem(str(info['Id'])))
        ui.tableWidget.setItem(index,1,QTableWidgetItem(str(info['Name'])))
        ui.tableWidget.setItem(index, 2, QTableWidgetItem(str(info['BLABLA'])))
        button = QPushButton("Addpatient")
        ui.tableWidget.setCellWidget(index, len(Table_information), button)
        index += 1


    win.setLayout(vbox)


#----------------Main------
Table_info()
win.show()
sys.exit(app.exec_())
